### Deployment ###
name: Build and deploy to Amazon Web Services
on:
  push: 
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"

  build-and-deploy:
    name: Build and deploy frontend to S3 and Cloudfront
    runs-on: ubuntu-latest
    env:
      BUCKET: www.sunnychen.au
      DIST: build
      REGION: ap-southeast-2
      DIST_ID: E2QUGB8EVMBE8U

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          node --version
          npm ci

      - name: Build Project
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to S3
        working-directory: ./frontend
        run: aws s3 sync ./${{ env.DIST }}/ s3://${{ env.BUCKET }} --delete

      # Invalidate cache so new changes actually show correctly
      - name: Invalidate the cache
        run: | 
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
